# Generated by Django 5.2.6 on 2025-09-06 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('audio_file', models.FileField(upload_to='audio_lines/')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_lines', to='file_reader.document')),
            ],
        ),
    ]
